version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: etsia-postgres
    environment:
      POSTGRES_DB: yansnet-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwertyuiop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etsia-network



  # Application Spring Boot
  backend:
    image: gfriedtod/yansnet:dev
    container_name: etsia-back
    ports:
      - "8085:8085"



volumes:
  postgres_data:
    driver: local

networks:
  etsia-network:
    driver: bridge
