spring.application.name=application
server.port=8085
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration = DEBUG
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
server.forward-headers-strategy=native

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/yansnet-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:qwertyuiop}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/yansnet}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/yansnet/protocol/openid-connect/certs}
# Keycloak Client Configuration
keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8090}
keycloak.realm=${KEYCLOAK_REALM:yansnet}
keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:yansnet-client-test-01}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:yansnet-client-test-01}

# MinIO Configuration
minio.url=${MINIO_URL:http://127.0.0.1:9000}
minio.public-url=${MINIO_PUBLIC_URL:http://127.0.0.1:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=${MINIO_BUCKET_NAME:yansnet-media}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# Token Configuration
auth.access-token-expiration=900000
auth.refresh-token-expiration=604800000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=50MB
